Resources:
  mainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.dbName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      BillingMode: PAY_PER_REQUEST
