Resources:
  mainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: haskell-todo-app
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      BillingMode: PAY_PER_REQUEST
