Resources:
  mainTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: haskell-todo-app
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE

      BillingMode: PAY_PER_REQUEST
