name: todo-app
version: 0.1.0.0
github: ""
license: BSD3
author: ""
maintainer: ""
copyright: ""

extra-source-files:
  - README.md
  - ChangeLog.md

description: "todo app"

dependencies:
  - base >= 4.7 && < 5
  - unordered-containers
  - pretty-simple
  - serverless-haskell
  - aeson
  - text
  - lens
  - amazonka-core
  - amazonka-dynamodb
  - amazonka
  - dotenv
  - filepath
  - directory
  - casing
  - time

library:
  source-dirs: src

executables:
  get-todos-exe:
    main: Main.hs
    source-dirs: app/get-todos
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - todo-app
